### ISSUE TITLE
Create OSW/Json elements inside Graph-Tool

### ISSUE THREAD

**Issue by MatPopp** [OpenSemanticLab/interactive-semantic-graph#24]
"push to OSW" => Save Elements from Graph as OSW elements

(Possibly from old Graph tool)

**Comment by MatPopp** [comment]
When Edit mode is active (i.e. the Edit ribbon is visible) and the user clicks into a white space inside the Graph-Tool:
* AND the "[generate new JSON](https://wiki-dev.open-semantic-lab.org/wiki/Item:OSW34ee6e9c3e7e45f2ab6357148dcad7ea)" checkbox is active:
   * a new (visible) node shall be created at the cursor position
   * a callback function will be called that opens a popup window 
   * * the default popup suggests all jsonschemas that are present in jsonschema (or none). It returns an object {new_jsondata:{type:<ch>,label:<label_from_input_in_popup>},new_jsondata_key:<Item:new_uuid>,....}
   * * the default popup can later be replaced by backend-specific popups
   * * in all cases the return value is an object { new_jsondata:<jsondata_object>,new_jsondata_key:<new_jsondata_key>,param2:<..>,...} 
   * a new jsondata element shall be created

* AND the "generate new JSON" checkbox is NOT checked
  * a new (visible) node shall be crated (with fixed position) at the cursor position
  * a popup window shall appear in which the user should type the label of the new node (conform with OK button)
  * the graph tool should switch to add edge mode => the user can draw an edge
  * a callback function will be called that opens a popup window 
  * in the default popup the user should type the key/poperty label
  * * if the key is not in context it should be used in jsondata as is (without being mapped to context)
  * * if the key is in context it can directly be used and displayed with the property name
  * * if the key is the name of a property the added key in jsondata should be accordingly 
  * (conform with OK button)
  * the physics

**Comment by simontaurus** [comment]
Add a Node (Instance):
1. Generate a list of all existing type = schema ids
2. Populate list, store selected type in created jsondata

Add an edge:
1. Generate aggregated context (e. g. combine the Item and Entity `@context`)
```json
{
"@context": {
    "property_key": "property_name",
    "member": {"@id": "Property:HasMember", "@type": "@id"},
  }
}
```
3. Populate autocomplete / dropdown with all available Properties, in this case ["Property:HasMember"]
4. User types property_name or select one from the suggestion list
5. Lookup property_name => key in the aggregated context
6. Case property_name (e. g. Property:HasMember or HasMember) in context: get the property_key (here `member`) and store "key": "id of the node the edge points to" in the jsondata of the node the edge originates from
```json
{
  "<property_key>": [
    "<id of the node the edge points to>"
  ]
}
```
7. Case not in context: Store the property_name as statement (s. a. [example](https://wiki-dev.open-semantic-lab.org/wiki/Item:OSWe55957abec4d417683e2daade8c68efd))
```json
{
  "statements": [
    {
      "uuid": "78b3f6f9-d1b8-4103-9bf5-7486dc21703b",
      "predicate": "<property_name>",
      "object": "<id of the node the edge points to>"
    }
  ]
}
```
